id = 10
title = "CTF IRL"
short = "CTF IRL" 
date = "Friday 3/3 6:00PM-8:00PM PT"
description = """#### Y'all loved the first one so much, we're back with another one! 
Come join us on the **IM field** from **6-8PM on Friday, 3/3**, where you get to play, yes Capture the Flag. You heard that right. Because what's Cyber without CTFs? Run around and touch grass to your heart's content as we compete in teams to actually grab flags and see nature as it was intended to be: not on a computer screen as an image."""
link = ""
slides = ""
