slug = "cookies"
title = "Cookies"
author = "Emily Sun"
value = 20
description = """I have a trade offer for you. The challenge is at [https://cookies.acmcyber.com](https://cookies.acmcyber.com)"""
tags = [ "intro" ]
files = []
flag = "flag{c00k135_g0_brrr}"
enabled = true 
