slug = "bank"
title = "Bank"
author = "Daniel Ynag"
value = 10
description = """This is a bank. I hate php very much. [Here](https://bank.acmcyber.com/)"""
tags = [ "sqli" ]
files = []
flag = "flag{ifrigginhatephpkillmenow}"
enabled = true 
