slug = "sql-prevention-101"
title = "SQL Prevention-101"
author = "Gary"
value = 30
description = """Just try to hack my [login](https://sql-prevention-101.acmcyber.com/) with account "admin", I've taken all the precautions that I can..."""
tags = ["SQL"]
files = []
flag = "flag{curse_you_mysql!}"
enabled = true