version: '3.9'

services:
  app:
    build: ./src
    networks:
      - app-network
    ports:
      - 5001:5000
    depends_on:
      - db
    links:
      - db
  
  db:
    build: ./db
    networks:
      - app-network
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: appdb
      MARIADB_USER: app
      MARIADB_PASSWORD: password

networks:
  app-network:
    driver: bridge