id = 12
title = "PBR Practice"
short = "PBR Practice" 
date = "Tuesdays 6:00PM-8:00PM PT"
description = """#### Want to be a hacker? 💻Come join Psi Beta Rho, ACM Cyber's competitive CTF team! 🥳 
CTFs or Capture-the-Flags are competitions where you solve cybersecurity problems to earn points. 💯 This is a great opportunity to add to your resume and build on the skills you have learned at the Cyber Academy and Special Topics Tracks! 📄😎 We will be having our weekly practice on **Tuesdays from 6-8 pm**. Location at **Ackerman Union 3517**. **NO EXPERIENCE NECESSARY!** All skill levels and experiences are welcome! Be sure to invite your friends!"""
link = ""
slides = ""
