slug = "simple-calculator"
title = "Simple Calculator"
author = "Jason An"
value = 30
description = """[Check out my new calculator!](https://simple-calculator.acmcyber.com/)"""
tags = [ "lfi" ]
files = []
flag = "flag{how_do_i_make_my_calculator_work_for_more_inputs}"
enabled = true 
