id = 11
title = "CTF After Dark Kickoff"
short = "CTF After Dark" 
date = "Wednesday 3/1 6:00PM-8:00PM PT"
description = """#### 🔥Get ready to flex your cyber skills and bring your A-game to the ultimate test!🔥 
CTF After Dark is back and better than ever! 💭You've been training hard all quarter long and now it's time to put your knowledge to the test. 🏋️We've got 9️⃣ flights of stairs worth of challenges waiting for you, all related to web hacking. 🦵🥵But don't worry, you're an absolute unit. A Cookie 🍪 Monster 🔵👄🔵 with a megamind brain 🧠 ready for anything that comes your way. 🙅🙅‍♀️🙅‍♂️Come play our 🚩 Capture the Flag (CTF) 🚩competition 🕸👨‍💻 and show off all that you've learned from our workshops this winter. Winners 🏅will be rewarded 👀, so don't miss out! Be there or be square 🟨."""
link = ""
slides = ""
