slug = "spiteful-xss"
title = "Spiteful XSS"
author = "Jason An"
value = 40
description = """Everyone keeps exploiting my site, [so I deleted all the globals.](https://spiteful-xss.acmcyber.com/)

[Admin Bot](https://admin-bot.acmcyber.com/spiteful-xss)"""
tags = [ "xss" ]
files = []
flag = "flag{when_has_giving_people_restricted_xss_ever_worked}"
enabled = true 
